### PR TITLE
New motherboard mappings and add numbers of links

### PR DESCRIPTION
**Pull request by jbsauvan**
- New motherboard mappings
- Add file containing the number of output links of each motherboard

### CODE REVIEW

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
+upgrade

**Comment by smuzaffar** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by smuzaffar** [comment]
@fabiocos , cmsdist PR to include it is https://github.com/cms-sw/cmsdist/pull/5019
which can be merged without tests as tests has been run here (and also this only include new files).

**Pull request merged**
