### PR TITLE
Add e/g BDT weights for the V10 and V11 geometries

### PR DESCRIPTION
**Pull request by jbsauvan**
Add e/gamma identification BDT weights trained with the V10 and V11 HGCAL geometries

### CODE REVIEW

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
@smuzaffar https://github.com/cms-sw/cmssw/pull/30289 is ready. Can we merge this PR ?

**Comment by mrodozov** [comment]
+externals
only new files

**Comment by silviodonato** [comment]
merge

**Pull request merged**
