### PR TITLE
Add new egamma ID weight files

### PR DESCRIPTION
**Pull request by jbsauvan**
Add BDT weight files for the egamma identification based on the "histomax" clustering

### CODE REVIEW

**Comment by mrodozov** [comment]
assign l1

**Comment by kpedro88** [comment]
@rekovic please sign this, otherwise the cmssw PR cannot move forward

**Comment by smuzaffar** [comment]
+externals

**Comment by kpedro88** [comment]
@rekovic ping

**Comment by rekovic** [comment]
+1

**Comment by kpedro88** [comment]
+1
@mrodozov can you create the new tag so the cmsdist PR can be used for testing?

**Comment by mrodozov** [comment]
@kpedro88 tag 12  is available now

**Pull request merged**
