### PR TITLE
Fixes and updates in the geometry mappings

### PR DESCRIPTION
**Pull request by jbsauvan**
- Fix compatibility of the trigger cell mapping with the V9 geometry
- Update tower mappings

### CODE REVIEW

**Comment by mrodozov** [comment]
assign l1

**Comment by mrodozov** [comment]
can I have approval please

**Comment by kpedro88** [comment]
@rekovic,@nsmith-,@thomreis please review and approve

**Comment by kpedro88** [comment]
@rekovic,@nsmith-,@thomreis ping

**Comment by thomreis** [comment]
I can approve it but I have to take your word for it that you know what those numbers mean. Github does not even want to display the files.

**Comment by thomreis** [comment]
+1

**Comment by jbsauvan** [comment]
Hi @thomreis, these files are indeed huge and we'll move to a a less memory-hungry solution in the future. For the moment we need to map HGCAL cells to trigger cells and trigger cells to trigger towers this way and there are a lot of cells and trigger cells in the HGCAL.

**Pull request merged**
