### PR TITLE
Add module to tower splitting map

### PR DESCRIPTION
**Pull request by jbsauvan**
- Add map of modules to towers in order to share module energies into several intersecting towers

### CODE REVIEW

**Comment by aloeliger** [comment]
@jbsauvan Could I quiz you a little bit on what this is and what it is intended for? I don't see any other tower mapping off this type present yet.

**Comment by aloeliger** [comment]
Ahh, okay, I see https://github.com/cms-sw/cmssw/pull/42246 now. Nevermind.

**Comment by aloeliger** [comment]
+l1

**Comment by rappoccio** [comment]
please test

* Refreshing tests.

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
