### PR TITLE
Update module mapping for V11

### PR DESCRIPTION
**Pull request by jbsauvan**
Update mapping for V11 after the changes in the cell validity checks implemented in cms-sw/cmssw#30323

### CODE REVIEW

**Comment by silviodonato** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
@cmsbuild  ping

**Comment by silviodonato** [comment]
@smuzaffar  @mrodozov I didn't get the `cms-dist` pull request.  I did not manage to make it manually on time, so also the 11pm IB will be bugged :-( .

**Comment by smuzaffar** [comment]
let me check

**Comment by smuzaffar** [comment]
@silviodonato cms-sw/cmsdist#6017 is now available and has been merged for next 11.2.X Ib

**Comment by silviodonato** [comment]
Many thanks @smuzaffar !!

**Pull request merged**
