### PR TITLE
Add V11 mappings

### PR DESCRIPTION
**Pull request by jbsauvan**
Add modules and links mappings for the V11 HGCAL geometry

### CODE REVIEW

**Comment by kpedro88** [comment]
@smuzaffar @mrodozov the tests completed in https://github.com/cms-sw/cmssw/pull/29400, but didn't show up complete here?

**Comment by kpedro88** [comment]
@smuzaffar @mrodozov ping

**Comment by smuzaffar** [comment]
@kpedro88 , looks like the jenkins job only started the test for cmssw. May be there were two jobs in jenkins queue (one with cmssw only and other with cmssw+data) and one killed the other. Anyway, I have restarted the test now

**Comment by smuzaffar** [comment]
+externals

**Comment by silviodonato** [comment]
merge
@benkrikler @rekovic @kpedro88

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
