### PR TITLE
Add mappings for decentralized ECON architecture

### PR DESCRIPTION
**Pull request by jbsauvan**
- Add panel and link mappings for the decentralized ECON architecture 
- Also updates older mappings used for the centralized ECON architecture

### CODE REVIEW

**Comment by kpedro88** [comment]
+upgrade

**Comment by jbsauvan** [comment]
Tests failed because of input file opening errors, unrelated to HGCAL (or Phase 2)

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar I will merge this to get #28385 fully operational

@rekovic FYI

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
this only contains new data files. So I am merging it here. @fabiocos , there will be a cmsdist PR to include it. Please merge that PR to go with cms-sw/cmssw#28385

**Comment by fabiocos** [comment]
@smuzaffar thanks, the cmsdist PR is exactly what I wanted to trigger in time for this evening...

**Pull request merged**
