### PR TITLE
Add egamma BDT weight files

### PR DESCRIPTION
**Pull request by jbsauvan**
Retrained egamma id BDTs with new trigger primitives (V9 geometry, latest clustering version)

### CODE REVIEW

**Comment by rekovic** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Comment by kpedro88** [comment]
+upgrade

**Comment by smuzaffar** [comment]
@fabiocos , should we merge this too. Only new files

**Comment by fabiocos** [comment]
+1

**Pull request merged**
